# Generated by Django 4.1 on 2023-01-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proffessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=20)),
                ("ename", models.CharField(max_length=100)),
            ],
            options={"db_table": "proffessor",},
        ),
    ]
